### ISSUE TITLE
Error write_text raise Not Implemented

### ISSUE THREAD

**Issue by suhanyaPrasad** [jodyphelan/malaria-profiler#14]
Hi, I am getting errors in the writing output stage. Please see attached error file.  
Traceback (most recent call last):
  File "/home/anaconda3/envs/mp/bin/malaria-profiler", line 487, in <module>
    args.func(args)
  File "/home/anaconda3/envs/mp/bin/malaria-profiler", line 172, in main_profile
    mp.write_outputs(args,result)
  File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/malaria_profiler/output.py", line 29, in write_outputs
    write_text(result,args.conf,text_output)
  File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/malaria_profiler/output.py", line 136, in write_text
    raise NotImplemented

How do I proceed with the commands ? 
[malaria-profile-error.txt](https://github.com/user-attachments/files/16070596/malaria-profile-error.txt)

**Comment by jodyphelan** [comment]
I've just put in a fix in v0.0.6. If you run
`pip install --force-reinstall git+https://github.com/jodyphelan/malaria-profiler.git@dev` to install the latest version, it should work after that.
